version: '2.1'

services:
  sut:
    image: balena/jellyfish-sut:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    secrets:
      - integration_front_token
      - integration_intercom_token
    networks:
      - internal

secrets:
  integration_front_token:
    file: ./.balena/secrets/integration_front_token
  integration_intercom_token:
    file: ./.balena/secrets/integration_intercom_token
