version: "3.9"

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - LOGLEVEL=error
    networks:
      - internal
