version: '3'

env:
  INTEGRATION_FRONT_TOKEN:
    sh: cat /run/secrets/integration_front_token
  INTEGRATION_INTERCOM_TOKEN:
    sh: cat /run/secrets/integration_intercom_token

tasks:
  test:
    cmds:
      - node ./scripts/delete-test-conversations.js
      - npm run test:integration
